package src.Mensaje;

public enum TipoMensaje {
    MENSAJE_CONEXION, MENSAJE_CONFIRMACION_CONEXION,
    MENSAJE_LISTA_USUARIOS, MENSAJE_CONFIRMACION_LISTA_USUARIOS,
    MENSAJE_LISTA_FICHEROS, MENSAJE_CONFIRMACION_LISTA_FICHEROS,
    MENSAJE_PEDIR_FICHERO, MENSAJE_EMITIR_FICHERO, MENSAJE_FICHERO_NO_EXISTENTE,
    MENSAJE_PREPARADO_CLIENTE_SERVIDOR, MENSAJE_PREPARADO_SERVIDOR_CLIENTE,
    MENSAJE_CERRAR_CONEXION, MENSAJE_CONFIRMACION_CERRAR_CONEXION
}
